name: xeus-sql
channels:
  - conda-forge
dependencies:
  - xeus
  - cppzmq
  - zeromq
  - nlohmann_json
  - xtl
  - cpp-tabulate>=1.3,<2
  - soci-core
  - xvega>=0.0.4
  - xproperty
  - xvega-bindings
