name: xeus-sql
channels:
  - conda-forge
dependencies:
  # Builde dependencies
  - cmake
  # host dependencies
  - xeus
  - cppzmq
  - zeromq
  - nlohmann_json
  - xtl
  - cpp-tabulate
  - soci-core
  - xproperty
  - xvega-bindings
  - xvega
