name: xeus-sql
channels:
  - conda-forge
dependencies:
  - cmake
  - xeus
  - cppzmq
  - zeromq
  - nlohmann_json
  - xtl
  - cpp-tabulate
  - xproperty
  - xvega-bindings
  - xvega
  - xeus-sql=0.0.7
  - soci-sqlite
  - soci-core
